### ISSUE TITLE
Instant anorm Column parser exception

### ISSUE THREAD

**Issue by KapStorm** [oyvindberg/typo#33]
With a basic database
```sql
CREATE TABLE users(
  user_id UUID NOT NULL,
  created_at TIMESTAMPTZ NOT NULL
)
```
and override `created_at` type to `java.time.Instant`
```scala
val options = Options(
      pkg = "org.foo.generated",
      dbLib = Some(DbLibName.Anorm),
      jsonLibs = List(JsonLibName.PlayJson),
      enableDsl = true,
      typeOverride = TypeOverride
        .of {
          case (
                RelationName(Some("public"), "users"),
                ColName("created_at")
              ) =>
            "java.time.Instant"
        }
}
```

I get an AnormException when I try to do something in the `UsersRepoImpl`
```scala
UsersRepoImpl.insert(
    UsersRow(
      userId = TypoUUID.randomUUID,
      createdAt = Instant.now()
    )
  )

Exception in thread "main" java.lang.ExceptionInInitializerError
        at Main.main(Main.scala)
Caused by: anorm.AnormException: TypeDoesNotMatch(Cannot convert 2023-09-13 17:42:16.253765-07: java.lang.String to Java8 Instant for column ColumnName(.created_at,Some(created_at)))
```

Libs using scala-cli
```scala
//> using scala "3.3.0"

//> using lib "com.olvind.typo::typo:0.3.0"
//> using lib "com.olvind.typo::typo-dsl-anorm:0.3.0"
//> using lib "com.typesafe.play::play-json::2.10.0-RC9"
```

**Comment by oyvindberg** [comment]
Sorry, I'll just have to disallow this usage.

So long story short, none of the date/time data types work precisely through postgres <-> jdbc <-> scala with anorm/doobie pipeline, maybe with the exception of `LocalDate`. Either offsets are lost, arrays don't work, or they lose precision. It's all a terrible state of affairs. 

As a result Typo introduces [custom types](https://oyvindberg.github.io/typo/docs/type-safety/date-time/) for this, which require us to go through a textual representation. To make that work, explicit casts are inserted into the generated sql. 
When you change the scala types, anorm's instances are not enthusiastic about receiving strings.
 
The new documentation for [user-defined types](https://oyvindberg.github.io/typo/docs/type-safety/user-selected-types/) specifies what they should be used for.

I get that you probably don't like these wrapper types, and that's fair. But it's super clear, and the generated row types belong in your database layer anyway. as do these wrapper types - it's just a matter of writing some manual (but compiler-checked) mapping code to your domain objects in your code. 
I guess the compromise is that type-safety is more important than convenience in this particular case.
