### ISSUE TITLE
Document Selector and filtering by selector

### ISSUE THREAD

**Issue by sbrunk** [oyvindberg/typo#70]
I just realized that it's already quite simple to filter out certain schemas/tables etc. via `Selector`. I.e.
```scala  
val selector = 
  (Selector.schemas("public") or
  (Selector.schemas("other") and Selector.relationNames("table_a", "table_b", "table_c")))

  generateFromDb(options, selector=selector, scriptsPaths = List(scriptsFolder))
    .overwriteFolder(folder = targetDir)
```

I think it could be useful to have that in the docs with a few examples. Especially as using this can reduce compile times on dbs with many tables :)

**Comment by oyvindberg** [comment]
Good point! It used to be required to specify it, so users would have to discover it. It gained a default however, so it should go in the docs.

I suggest a variable with a comment in the script on the getting started page, as well as a comment on the page about compile speed.
