### ISSUE TITLE
0.8.0 breaks when running on Scala 3.3.x

### ISSUE THREAD

**Issue by sbrunk** [oyvindberg/typo#87]
Probably because it is built with 3.4.0 now, causing forward compatiblity issues. In my case, it's not a big deal because I'm just running a scala-cli script but I wonder if it would be better to stay with an LTS version to avoid compat issues if people use Typo as a library/in their build etc.

https://www.scala-lang.org/blog/2022/08/17/long-term-compatibility-plans.html#library-maintainers

```
Error: error while loading Options,
class file typo/Options.class is broken, reading aborted with class dotty.tools.tasty.UnpickleException
TASTy signature has wrong version.
 expected: {majorVersion: 28, minorVersion: 3}
 found   : {majorVersion: 28, minorVersion: 4}

This TASTy file was produced by a more recent, forwards incompatible release.
To read this TASTy file, please upgrade your tooling.
The TASTy file was produced by Scala 3.4.0.
```

**Comment by oyvindberg** [comment]
Oh yeah, that'a a good point - hadn't thought about it.

My goal was to compile the generated code without warnings on scala 3.4, and the easiest way was to bump the entire build. 

It should be easy to compile with different scala versions:
- main projects (`typo`, `typo-dsl-*`): newest 3.3
- non-published projects (`typo-tester-*`, `scripts`, etc): newest 3.4
